### ISSUE TITLE
Backward compatibility (discussion)

### ISSUE THREAD

**Issue by Andreas-Forster** [unibas-gravis/scalismo-native#4]
We are a bit behind the newest available library versions from our native libs. Especially for VTK we are still relying on 6.2 while there is now 8.2 out. In the backward compatibility list there are very old OSs listed (Win XP, OS 10.7 Lion, Ubuntu 10.04 / Scientific Linux 5.10).

What is your opinion on using "newer" oldest versions of the different OSs when we tackle an update of our native libs? Some of old OS versions are around 10 years old.

**Comment by marcelluethi** [comment]
This issue is addressed with the latest scalismo release.
